version: '3'
#services:
#  db:
#    image: postgres:9.6
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=trains
#    healthcheck:
##      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
#      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
#      interval: 10s
#      retries: 5
#      timeout: 10s
#    restart: always
#    ports:
#      - 5432:5432
#
#  flyway-myschema:
#    image: boxfuse/flyway
##    image: flyway/flyway
##    command: -url=jdbc:postgresql://db:5432/trains -schemas="myschema,myschema2" -user=postgres -password=postgres -connectRetries=60 migrate
#    entrypoint: [ "bash" ]
#    #can use location for schemas, but versions cannot be the same
#    #-locations=filesystem:/flyway/sql/sc1
#    command: -c "/flyway/flyway -url=jdbc:postgresql://db:5432/trains -user=postgres -password=postgres -schemas=myschema migrate"
##                 /flyway/flyway -url=jdbc:postgresql://db:5432/trains -user=postgres -password=postgres -schemas=myschema2 migrate"
#    volumes:
#      - ./flyway/migrations/sc1:/flyway/sql/sc1
##      - ./flyway/migrations/sc2:/flyway/sql/sc2
##      - ./flyway/migrations:/flyway/sql
##      - ./flyway/migrations:/flyway/sql
#    depends_on:
#      db:
#        condition: service_healthy
#
#  flyway-myschema2:
#    image: boxfuse/flyway
#    #    image: flyway/flyway
#    #    command: -url=jdbc:postgresql://db:5432/trains -schemas="myschema,myschema2" -user=postgres -password=postgres -connectRetries=60 migrate
#    entrypoint: [ "bash" ]
#    #can use location for schemas, but versions cannot be the same
#    #-locations=filesystem:/flyway/sql/sc1
#    command: -c "/flyway/flyway -url=jdbc:postgresql://db:5432/trains -user=postgres -password=postgres -schemas=myschema2 migrate"
#    #      -c "/flyway/flyway -url=jdbc:postgresql://db:5432/trains -user=postgres -password=postgres migrate;"
#    volumes:
#      - ./flyway/migrations/sc2:/flyway/sql/sc2
##      - ./flyway/migrations:/flyway/sql
#    depends_on:
#      db:
#        condition: service_healthy
#
##volumes:
##    - db: